spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/survey_db
    username: postgres
    password: Admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

app:
  jwt:
    secret: mi_clave_secreta_muy_larga_y_segura_123456
    expiration: 86400000
